### ISSUE TITLE
Current TODO list

### ISSUE THREAD

**Issue by genkimarshall** [genkimarshall/vim-fold-notes#1]
- [ ] Add script to output HTML/markdown format of the notes
- [ ] Bug: the autoformat odesn't correctly indent the next line if the last character is a space.
- [ ] Use commands with hotkeys instead of macros stored in registers.
- [ ]  I like to keep my txt notes in a git repository. Maybe some helpers for this?
- [ ] Add a command to search file for dead/invalid relative paths.
